🚧 UNFINISHED ❌ Update by generate-modules-sdk
Full error log:
╭──────────────────────────────────────────────────────────────────────────────╮
╰──────────────────────────────────────────────────────────────────────────────╯

[2K[1A[2K[1A[2K[G╭──────────────────────────────────────────────────────────────────────────────╮
│╭────────────────────────────────────────────────────────────────────────────╮│
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Initialized                                                           │││
││└──────────────────────────────────────────────────────────────────────────┘││
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Spawning Browser                                                      │││
│││[⧖] Connection from Collboard (http://localhost:3000/open-collboard)      │││
││└──────────────────────────────────────────────────────────────────────────┘││
││To open additional window http://localhost:3000/open-collboard              ││
│╰────────────────────────────────────────────────────────────────────────────╯│
╰──────────────────────────────────────────────────────────────────────────────╯

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G╭──────────────────────────────────────────────────────────────────────────────╮
│╭────────────────────────────────────────────────────────────────────────────╮│
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Initialized                                                           │││
││└──────────────────────────────────────────────────────────────────────────┘││
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Spawning Chrome                                                       │││
│││[⧖] Connection from Collboard (http://localhost:3000/open-collboard)      │││
││└──────────────────────────────────────────────────────────────────────────┘││
││To open additional window http://localhost:3000/open-collboard              ││
│╰────────────────────────────────────────────────────────────────────────────╯│
╰──────────────────────────────────────────────────────────────────────────────╯

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G╭──────────────────────────────────────────────────────────────────────────────╮
│╭────────────────────────────────────────────────────────────────────────────╮│
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Compiling                                                             │││
││└──────────────────────────────────────────────────────────────────────────┘││
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Spawning Chrome                                                       │││
│││[⧖] Connection from Collboard (http://localhost:3000/open-collboard)      │││
││└──────────────────────────────────────────────────────────────────────────┘││
││To open additional window http://localhost:3000/open-collboard              ││
│╰────────────────────────────────────────────────────────────────────────────╯│
╰──────────────────────────────────────────────────────────────────────────────╯

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G╭──────────────────────────────────────────────────────────────────────────────╮
│╭────────────────────────────────────────────────────────────────────────────╮│
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Postprocessing                                                        │││
││└──────────────────────────────────────────────────────────────────────────┘││
││┌──────────────────────────────────────────────────────────────────────────┐││
│││[⧖] Spawning Chrome                                                       │││
│││[⧖] Connection from Collboard (http://localhost:3000/open-collboard)      │││
││└──────────────────────────────────────────────────────────────────────────┘││
││To open additional window http://localhost:3000/open-collboard              ││
│╰────────────────────────────────────────────────────────────────────────────╯│
╰──────────────────────────────────────────────────────────────────────────────╯

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G╭──────────────────────────────────────────────────────────────────────────────╮
│Error:  asset                                                                 │
│[1m[32m2022-7-24--19-39-32--dcac9057-1343-468c-97f2-ef90aaf442c0/main.min.js[39m[22m 61.3 KiB│
│ [1m[32m[emitted][39m[22m (name: main) 1 related asset                                       │
│runtime modules 57 bytes 1 module                                             │
│javascript modules 57.8 KiB                                                   │
│  [1m./src/index.ts[39m[22m 123 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m [1m[31m[1 error][39m[22m                 │
│  [1m./src/gltf-import-module.ts[39m[22m 2.99 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m               │
│  [1m./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js[39m[22m 54.7 KiB      │
│[1m[33m[built][39m[22m [1m[33m[code generated][39m[22m                                                      │
│[1m./assets/text-file-icon.svg[39m[22m 42 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m                 │
│[1m./package.json[39m[22m 589 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m                             │
│                                                                              │
│[1m[31mERROR[39m[22m in [1mC:\Users\me\work\collboard\3d-support\src\index.ts[39m[22m                   │
│[1m./src/index.ts[39m[22m [1m[32m3:0-5[39m[22m                                                          │
│[1m[tsl] [1m[31mERROR[39m[22m[1m in C:\Users\me\work\collboard\3d-support\src\index.ts(3,1)        │
│      TS2552: Cannot find name '[1m[31merror[39m[22m[1m'. [1m[32mDid you mean '[1m[31mError[39m[22m[1m'?[39m[22m[1m[39m[22m                 │
│                                                                              │
│webpack 5.35.1 compiled with [1m[31m1 error[39m[22m in 4752 ms                               │
╰──────────────────────────────────────────────────────────────────────────────╯

Error:  asset [1m[32m2022-7-24--19-39-32--dcac9057-1343-468c-97f2-ef90aaf442c0/main.min.js[39m[22m 61.3 KiB [1m[32m[emitted][39m[22m (name: main) 1 related asset
runtime modules 57 bytes 1 module
javascript modules 57.8 KiB
[1m./src/index.ts[39m[22m 123 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m [1m[31m[1 error][39m[22m
[1m./src/gltf-import-module.ts[39m[22m 2.99 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
[1m./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js[39m[22m 54.7 KiB [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
[1m./assets/text-file-icon.svg[39m[22m 42 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m
[1m./package.json[39m[22m 589 bytes [1m[33m[built][39m[22m [1m[33m[code generated][39m[22m

[1m[31mERROR[39m[22m in [1mC:\Users\me\work\collboard\3d-support\src\index.ts[39m[22m
[1m./src/index.ts[39m[22m [1m[32m3:0-5[39m[22m
[1m[tsl] [1m[31mERROR[39m[22m[1m in C:\Users\me\work\collboard\3d-support\src\index.ts(3,1)
TS2552: Cannot find name '[1m[31merror[39m[22m[1m'. [1m[32mDid you mean '[1m[31mError[39m[22m[1m'?[39m[22m[1m[39m[22m

webpack 5.35.1 compiled with [1m[31m1 error[39m[22m in 4752 ms
Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\3d-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\3d-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\3d-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\3d-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\3d-support\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\3d-support\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\3d-support\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\3d-support\node_modules\webpack\lib\Watching.js:201:28)

🏭 This commit was automatically generated by generate-modules-sdk script.